# Compiles harness and minimum framework code needed to use the state machine.
all:
	g++ -std=c++11 Main.cpp -I../../../../                                     \
	../../../core/StateVector.cpp                                              \
	../../../core/Region.cpp                                                   \
	../../../core/Element.cpp                                                  \
	../../../core/MemOps.cpp                                                   \
	../../../core/StateMachine.cpp                                             \
	../../../core/ExpressionStats.cpp                                          \
	../../../core/Expression.cpp                                               \
	../../../core/Action.cpp
