# Compiles harness and minimum framework code needed to use the state vector.
all:
	g++ -std=c++11 Main.cpp -I../../../../                                     \
	../../../core/StateVector.cpp                                              \
	../../../core/Region.cpp                                                   \
	../../../core/Element.cpp                                                  \
	../../../core/MemOps.cpp
